### ISSUE TITLE
calling setState after unattached scroll

### ISSUE THREAD

**Issue by yokoi-engineering** [AlexBacich/sticky-headers-table#30]
After calling setState (), I get not attached scrolling exception. Is there any alternative?

```
      rowsTitleBuilder: (i) => ExpansionTile(
          title: Text(row[i].name),
          onExpansionChanged: (value) {
            setState(() {});
          },
        )
```

```
======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
ScrollController not attached to any scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 171 pos 12: '_positions.isNotEmpty'
When the exception was thrown, this was the stack: 
#2      ScrollController.jumpTo (package:flutter/src/widgets/scroll_controller.dart:171:12)
#3      _SyncScrollController.processNotification (package:table_sticky_headers/table_sticky_headers.dart:348:22)
#4      _StickyHeadersTableState.build.<anonymous closure> (package:table_sticky_headers/table_sticky_headers.dart:256:53)
#5      Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:3966:39)
#6      Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:138:13)
...
Handler: "onUpdate"
Recognizer: VerticalDragGestureRecognizer#9818c
  start behavior: start
====================================================================================================
```

**Comment by yokoi-engineering** [comment]
using table_sticky_headers 2.0.0

```
Flutter 2.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision adc687823a (3 weeks ago) • 2021-04-16 09:40:20 -0700
Engine • revision b09f014e96
Tools • Dart 2.12.3
```

**Comment by annguyen-it** [comment]
> using table_sticky_headers 2.0.0
> 
> ```
> Flutter 2.0.5 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision adc687823a (3 weeks ago) • 2021-04-16 09:40:20 -0700
> Engine • revision b09f014e96
> Tools • Dart 2.12.3
> ```

By some reasons, controllers have been "reset", I think.

First, you should define 4 ScrollController: `verticalBodyController`, `verticalTitleController`, `horizontalBodyController` and `horizontalTitleController`. Then you should assign `new ScrollController()` to them. Next, in StickyHeadersTable, you should do this:
```
ScoreTable(
                 scrollControllers: ScrollControllers(
                    verticalBodyController: widget._verticalBodyController,
                    verticalTitleController: widget._verticalTitleController,
                    horizontalBodyController: widget._horizontalBodyController,
                    horizontalTitleController: widget._horizontalTitleController,
                  ),
                )
```

See Controllers: https://github.com/AlexBacich/sticky-headers-table/blob/06031a1f3d7f8f78c8ecbfcd631b709840f14044/lib/table_sticky_headers.dart#L59

**Comment by yokoi-engineering** [comment]
Oh I see. I needed to keep scrollControllers in a state. Thank you.
